<a href="https://colab.research.google.com/github/masangshubham/WAD-College-Practicals/blob/main/B2(cleaning%2C_intergration%2Ctransformation%2C_model_building).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Perform the following operations using ‘python’ Language on the Heart
# Disease dataset.
# 1) Data cleaning
# 2) Data integration
# 3) Data transformation
# 4) Data model Building

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
df=pd.read_csv("/content/heart.csv")
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  target  
0         2   2     3       0  
1         0   0     3       0  
2         0   0     3       0  
3         2   1     3       0  
4         1   3     2       0  
...     ...  ..   ...     ...  
1020      2   0     2       1  
1021      1   1     3       0  
1022      1   1     2       0  
1023      2   0     2       1  
1024      1   1     3       0  

[1025 rows x 14 columns]

In [ ]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [ ]:
df.describe()

age          sex           cp     trestbps        chol  \
count  1025.000000  1025.000000  1025.000000  1025.000000  1025.00000   
mean     54.434146     0.695610     0.942439   131.611707   246.00000   
std       9.072290     0.460373     1.029641    17.516718    51.59251   
min      29.000000     0.000000     0.000000    94.000000   126.00000   
25%      48.000000     0.000000     0.000000   120.000000   211.00000   
50%      56.000000     1.000000     1.000000   130.000000   240.00000   
75%      61.000000     1.000000     2.000000   140.000000   275.00000   
max      77.000000     1.000000     3.000000   200.000000   564.00000   

               fbs      restecg      thalach        exang      oldpeak  \
count  1025.000000  1025.000000  1025.000000  1025.000000  1025.000000   
mean      0.149268     0.529756   149.114146     0.336585     1.071512   
std       0.356527     0.527878    23.005724     0.472772     1.175053   
min       0.000000     0.000000    71.000000     0.000000     0.000000   
25%       0.000000     0.000000   132.000000     0.000000     0.000000   
50%       0.000000     1.000000   152.000000     0.000000     0.800000   
75%       0.000000     1.000000   166.000000     1.000000     1.800000   
max       1.000000     2.000000   202.000000     1.000000     6.200000   

             slope           ca         thal       target  
count  1025.000000  1025.000000  1025.000000  1025.000000  
mean      1.385366     0.754146     2.323902     0.513171  
std       0.617755     1.030798     0.620660     0.500070  
min       0.000000     0.000000     0.000000     0.000000  
25%       1.000000     0.000000     2.000000     0.000000  
50%       1.000000     0.000000     2.000000     1.000000  
75%       2.000000     1.000000     3.000000     1.000000  
max       2.000000     4.000000     3.000000     1.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1025 non-null   int64  
 1   sex       1025 non-null   int64  
 2   cp        1025 non-null   int64  
 3   trestbps  1025 non-null   int64  
 4   chol      1025 non-null   int64  
 5   fbs       1025 non-null   int64  
 6   restecg   1025 non-null   int64  
 7   thalach   1025 non-null   int64  
 8   exang     1025 non-null   int64  
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64  
 11  ca        1025 non-null   int64  
 12  thal      1025 non-null   int64  
 13  target    1025 non-null   int64  
dtypes: float64(1), int64(13)
memory usage: 112.2 KB


In [ ]:
df.dropna(thresh=0.5*len(df),axis=1)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  target  
0         2   2     3       0  
1         0   0     3       0  
2         0   0     3       0  
3         2   1     3       0  
4         1   3     2       0  
...     ...  ..   ...     ...  
1020      2   0     2       1  
1021      1   1     3       0  
1022      1   1     2       0  
1023      2   0     2       1  
1024      1   1     3       0  

[1025 rows x 14 columns]

In [ ]:
df1=df[['age','sex','cp','ca']].loc[0:15]
df1

age  sex  cp  ca
0    52    1   0   2
1    53    1   0   0
2    70    1   0   0
3    61    1   0   1
4    62    0   0   3
5    58    0   0   0
6    58    1   0   3
7    55    1   0   1
8    46    1   0   0
9    54    1   0   2
10   71    0   0   0
11   43    0   0   0
12   34    0   1   0
13   51    1   0   3
14   52    1   0   0
15   34    0   1   0

In [ ]:
df2=df[['age','sex','cp','ca']].loc[16:30]
df2

age  sex  cp  ca
16   51    0   2   1
17   54    1   0   1
18   50    0   1   0
19   58    1   2   0
20   60    1   2   0
21   67    0   0   2
22   45    1   0   0
23   63    0   2   0
24   42    0   2   0
25   61    0   0   0
26   44    1   2   0
27   58    0   1   2
28   56    1   2   1
29   55    0   0   0
30   44    1   0   0

In [ ]:
df3=df[['age','sex','cp','ca']].loc[31:45]
df3

age  sex  cp  ca
31   50    0   1   0
32   57    1   0   1
33   70    1   2   1
34   50    1   2   0
35   46    1   2   0
36   51    1   3   1
37   59    1   0   0
38   64    1   0   1
39   57    1   2   1
40   65    0   2   0
41   54    1   2   0
42   61    0   0   0
43   46    1   0   0
44   55    0   1   0
45   42    1   0   0

In [ ]:
merge=pd.merge(df1,df2,on='age',how='inner')
merge

age  sex_x  cp_x  ca_x  sex_y  cp_y  ca_y
0   61      1     0     1      0     0     0
1   58      0     0     0      1     2     0
2   58      0     0     0      0     1     2
3   58      1     0     3      1     2     0
4   58      1     0     3      0     1     2
5   55      1     0     1      0     0     0
6   54      1     0     2      1     0     1
7   51      1     0     3      0     2     1

In [ ]:
df['target']=df['target'].apply(lambda x:1.5 if x>0 else 0)
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  target  
0         2   2     3     0.0  
1         0   0     3     0.0  
2         0   0     3     0.0  
3         2   1     3     0.0  
4         1   3     2     0.0  
...     ...  ..   ...     ...  
1020      2   0     2     1.5  
1021      1   1     3     0.0  
1022      1   1     2     0.0  
1023      2   0     2     1.5  
1024      1   1     3     0.0  

[1025 rows x 14 columns]

In [ ]:
df = df.applymap(lambda x: df.mean() if x<0 else x) 
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  target  
0         2   2     3     0.0  
1         0   0     3     0.0  
2         0   0     3     0.0  
3         2   1     3     0.0  
4         1   3     2     0.0  
...     ...  ..   ...     ...  
1020      2   0     2     1.5  
1021      1   1     3     0.0  
1022      1   1     2     0.0  
1023      2   0     2     1.5  
1024      1   1     3     0.0  

[1025 rows x 14 columns]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X=merge.drop(['age'],axis=1)
Y=merge['age']

In [ ]:
X_train, X_test, Y_train,Y_test= train_test_split(X,Y,test_size=0.3,random_state=42)

In [ ]:
from sklearn.linear_model import LogisticRegression
logreg=LogisticRegression();
logreg.fit(X_train,Y_train)

LogisticRegression()

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
y_pred = logreg.predict(X_test)
print(confusion_matrix(Y_test,y_pred))
print(classification_report(Y_test,y_pred,zero_division=0))

[[0 0 0 0]
 [1 0 0 0]
 [0 0 1 0]
 [1 0 0 0]]
              precision    recall  f1-score   support

          54       0.00      0.00      0.00         0
          55       0.00      0.00      0.00         1
          58       1.00      1.00      1.00         1
          61       0.00      0.00      0.00         1

    accuracy                           0.33         3
   macro avg       0.25      0.25      0.25         3
weighted avg       0.33      0.33      0.33         3

